#!/bin/bash
function send-log(){
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>⚠️NOTIF QUOTA HABIS XRAY VLESS⚠️</b>
<code>────────────────────</code>
<code>Username  : </code><code>$user</code>
<code>Limit Quota: </code><code>$total2</code>
<code>Usage     : </code><code>$total</code>
<code>────────────────────</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function con() {
  local -i bytes=$1;
  if [[ $bytes -lt 1024 ]]; then
      echo "${bytes}B"
  elif [[ $bytes -lt 1048576 ]]; then
      echo "$(( (bytes + 1023)/1024 ))KB"
  elif [[ $bytes -lt 1073741824 ]]; then
      echo "$(( (bytes + 1048575)/1048576 ))MB"
  else
      echo "$(( (bytes + 1073741823)/1073741824 ))GB"
  fi
}

while true; do
  sleep 60
  data=($(grep '^#&' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
  mkdir -p /etc/limit/vless

  for user in ${data[@]}; do
    downlink=$(xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" | grep -w "value" | awk '{print $2}' | cut -d '"' -f2)
    if [ -e /etc/limit/vless/${user} ]; then
      prev=$(cat /etc/limit/vless/${user})
      total=$((downlink + prev))
      echo "${total}" > /etc/limit/vless/${user}
      xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset >/dev/null 2>&1
    else
      echo "${downlink}" > /etc/limit/vless/${user}
      xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset >/dev/null 2>&1
    fi
  done

  for user in ${data[@]}; do
    if [ -e /etc/vless/${user} ]; then
      limit=$(cat /etc/vless/${user})
      [[ ${limit} -lt 1 ]] && continue
      usage=$(cat /etc/limit/vless/${user})
      [[ -z "$usage" ]] && continue

      if [[ ${usage} -gt ${limit} ]]; then
        total=$(con ${usage})
        total2=$(con ${limit})
        uuid=$(grep -wE "^},{" "/etc/xray/config.json" | grep -w "\"${user}\"" | cut -d '"' -f4 | uniq)
        exp=$(grep -wE "^#& $user" "/etc/xray/config.json" | cut -d" " -f3 | sort -u)
        sed -i '/#vless$/a\#& '"$user $exp $uuid"'' /etc/xray/.lock.db
        sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
        send-log
        rm -f /etc/limit/vless/${user}
        > /etc/vless/${user}
        systemctl restart xray >/dev/null 2>&1
      fi
    fi
  done
done
